// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0SIjIt22kHNGi6yVXPondqNZ4nIxKBWU',
    appId: '1:775128512500:web:39c1f5a732ca3ec6962ba1',
    messagingSenderId: '775128512500',
    projectId: 'qarep-1827d',
    authDomain: 'qarep-1827d.firebaseapp.com',
    storageBucket: 'qarep-1827d.firebasestorage.app',
    measurementId: 'G-PTWJMJ2HYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkm28zwZBnYG1GW2lzUNnbp9NF-yHakps',
    appId: '1:775128512500:android:0a3d6f782a4e4f81962ba1',
    messagingSenderId: '775128512500',
    projectId: 'qarep-1827d',
    storageBucket: 'qarep-1827d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiaXG1kVQiNeii56OAyZfoaSAVjnzPg_g',
    appId: '1:775128512500:ios:8fad545c80c61577962ba1',
    messagingSenderId: '775128512500',
    projectId: 'qarep-1827d',
    storageBucket: 'qarep-1827d.firebasestorage.app',
    iosBundleId: 'com.example.qaryp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiaXG1kVQiNeii56OAyZfoaSAVjnzPg_g',
    appId: '1:775128512500:ios:8fad545c80c61577962ba1',
    messagingSenderId: '775128512500',
    projectId: 'qarep-1827d',
    storageBucket: 'qarep-1827d.firebasestorage.app',
    iosBundleId: 'com.example.qaryp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0SIjIt22kHNGi6yVXPondqNZ4nIxKBWU',
    appId: '1:775128512500:web:c664a4fdedc0a0a5962ba1',
    messagingSenderId: '775128512500',
    projectId: 'qarep-1827d',
    authDomain: 'qarep-1827d.firebaseapp.com',
    storageBucket: 'qarep-1827d.firebasestorage.app',
    measurementId: 'G-6DZZK1K4RM',
  );
}
